"""song table creation

Revision ID: f6b6c2d5324a
Revises: 005d78d66702
Create Date: 2026-05-05 02:22:58.877267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b6c2d5324a'
down_revision = '005d78d66702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('artist', sa.String(length=200), nullable=True),
    sa.Column('album', sa.String(length=200), nullable=True),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('preview', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_album'), ['album'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_artist'), ['artist'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_song_id'), ['song_id'], unique=True)

    with op.batch_alter_table('liked_songs', schema=None) as batch_op:
        batch_op.alter_column('song_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.create_foreign_key(None, 'song', ['song_id'], ['id'])
        batch_op.drop_column('image')
        batch_op.drop_column('title')
        batch_op.drop_column('artist')
        batch_op.drop_column('album')
        batch_op.drop_column('preview')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liked_songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('album', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('artist', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('song_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_song_id'))
        batch_op.drop_index(batch_op.f('ix_song_artist'))
        batch_op.drop_index(batch_op.f('ix_song_album'))

    op.drop_table('song')
    # ### end Alembic commands ###
